# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379152aa46235cbb559b52f8905af2aa50b73410044c243337dc435d752d13d5d94dc3dbe2880ee8cecb7260518b92ee5a3cd69cb35994e954729bdb88a2c35b

test:
  secret_key_base: 6414bf001b308976c2ba9c3d857dd74b3bc7f7afda264516fb4691dbc63430018ad64a2a10ac4810af0579dcbbcdafc811e7d4018f739ac206419816c8cc0d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
